
services:
  mariadb:
    container_name: mariadb
    image: mariadb
    networks:
      - inception
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
      args:
        SQL_DATABASE: $SQL_DATABASE
        SQL_USER: $SQL_USER
        SQL_PASSWORD: $SQL_PASSWORD
        SQL_ROOT_PASSWORD: $SQL_ROOT_PASSWORD
    volumes:
      - mariadb:/var/lib/mysql
    env_file: .env
    restart: unless-stopped
    expose:
      - "3306"

  nginx:
    container_name: nginx
    image: nginx
    volumes:
      - wordpress_data:$WP_PATH
    networks:
      - inception
    depends_on:
      - wordpress
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
      args:
        WP_PATH: $WP_PATH
        WP_URL: $WP_URL
    env_file: .env
    ports:
      - "443:443"
    restart: on-failure

  wordpress:
    container_name: wordpress
    image: wordpress
    env_file: .env
    volumes:
      - wordpress_data:$WP_PATH
    networks:
      - inception
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    depends_on:
      - mariadb
    restart: on-failure
    expose:
      - "9000"

networks:
  inception:
    driver: bridge

volumes:
  wordpress_data:
    driver: local
    name: wordpress_data
    driver_opts:
      type: 'none'
      o: 'bind'
      device: $WORDPRESS_VOLUME_PATH
  mariadb:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: $MARIADB_VOLUME_PATH
